<a href="https://colab.research.google.com/github/HassanMehmood413/Machine-Learning/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
from typing import Concatenate
# Numpy basics
import numpy as np

# 1. Creating an array:
# arr = np.array([1,2,3,4,5])
# print(arr)

# 2. Array of zeros and ones:
# arr = np.zeros([4])
# print(arr)
# arr = np.ones([5])
# print(arr)

# 3. Range of array:
# range_arr = np.arange(8)
# print(range_arr)

# 4. Reshaping of array:
# arr = np.array([1,2,3,4,5,6])
# print(arr)
# reshape_arr = arr.reshape(2,3)
# print(reshape_arr)

# 5. Basic operations (Add, Multiply,Subtract,Division)
# arr1 = np.arange(10)
# arr2 = [1,2,3,4,5,1,2,3,4,5]
# add
# print(np.add(arr1,arr2))
# subtract
# print(np.subtract(arr1,arr2))
# Multiply
# print(np.multiply(arr1,arr2))
# Divide
# print(np.divide(arr1,arr2))

# 6. Array Statistics:
# arr2 = [1,2,3,4,5,1,2,3,4,5]
# print(np.mean(arr2))
# print(np.sum(arr2))
# print(np.min(arr2))
# print(np.max(arr2))

# 7. Indexing and Slicing
# arr2 = [1,2,3,4,5,1,2,3,4,5]
# print(arr2[0:5])

# 8. Random Numbers:
# print(np.random.randint(1111))
# print(np.random.rand(3))

# 9. Identity Matrix:
# Diagonal entries must be 1
# print(np.eye(4))

# 10. Flatten Array:
# Concat both array
# arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
# print(arr2.flatten())

# 11. Transpose of array/Matrix:
# arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
# print(arr2.transpose())

# 12. Concatenate two arrays:
# arr1 = np.array([1,2,3,4,5])
# arr2 = np.array([1,2,3,4,5])
# print(np.concatenate((arr1,arr2)))

# 13. Unique Elements in array:
# arr1 = np.array([1,1,2,2,3])
# print(np.unique(arr1))

# 14. Sum along axis:
# arr1 = np.array([[1,1,2],[11,22,33]])
# print(arr1)
# Axis  = 0 means y Axis
# Axis  = 0 means x Axis
# print(np.sum(arr1,axis = 0))




[[ 1  1  2]
 [11 22 33]]
[12 23 35]
